name: Generate Binaries-1

on:
  workflow_call:

concurrency:
  group: generate-binaries
  cancel-in-progress: true

jobs:
  build_requirements:
    name: ${{ matrix.build_linux }} • ${{ matrix.build_arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        build_arch: [ "amd64" ]
        build_linux: [ musllinux ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: bigcat88/py_bundler-dev
          path: py_bundler
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        uses: docker/build-push-action@v3
        with:
          context: .
          file: py_bundler/docker/bundle_release.Dockerfile
          build-args: |
            BUILD_IMG=ghcr.io/bigcat88/py_bundler-dev/${{ matrix.build_linux }}_${{ matrix.build_arch }}:latest
          platforms: linux/${{ matrix.build_arch }}
          push: false
          cache-from: type=gha,scope=binaries-${{ matrix.build_linux }}-${{ matrix.build_arch }}
          cache-to: type=gha,mode=min,scope=binaries-${{ matrix.build_linux }}-${{ matrix.build_arch }}
